
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoginController;
import javax.swing.JOptionPane;

/**
 *
 * @author thien
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    static String  sdt;
    static String password;
    static String userName;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelanhlogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanellogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_password_login = new javax.swing.JPasswordField();
        btn_dangnhap_login = new javax.swing.JButton();
        btn_thoat_login = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton_student_login = new javax.swing.JRadioButton();
        jRadioButton_admin_login = new javax.swing.JRadioButton();
        txt_userName_login = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ảnhlogin.jpg"))); // NOI18N
        jLabel2.setAutoscrolls(true);

        javax.swing.GroupLayout jPanelanhloginLayout = new javax.swing.GroupLayout(jPanelanhlogin);
        jPanelanhlogin.setLayout(jPanelanhloginLayout);
        jPanelanhloginLayout.setHorizontalGroup(
            jPanelanhloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelanhloginLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelanhloginLayout.setVerticalGroup(
            jPanelanhloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelanhloginLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanellogin.setForeground(new java.awt.Color(255, 255, 255));
        jPanellogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("SIGN IN");
        jPanellogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 280, 82, 34));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("USER NAME");
        jPanellogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 86, 26));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("PASSWORD");
        jPanellogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 86, 26));
        jPanellogin.add(txt_password_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 396, 200, 30));

        btn_dangnhap_login.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_dangnhap_login.setText("ĐĂNG NHẬP");
        btn_dangnhap_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhap_loginActionPerformed(evt);
            }
        });
        jPanellogin.add(btn_dangnhap_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, 35));

        btn_thoat_login.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_thoat_login.setText("THOÁT");
        btn_thoat_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoat_loginActionPerformed(evt);
            }
        });
        jPanellogin.add(btn_thoat_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 111, 35));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login-icon-png-27.png"))); // NOI18N
        jPanellogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 270, 274));

        buttonGroup1.add(jRadioButton_student_login);
        jRadioButton_student_login.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton_student_login.setText("STUDENT");
        jPanellogin.add(jRadioButton_student_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        buttonGroup1.add(jRadioButton_admin_login);
        jRadioButton_admin_login.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton_admin_login.setText("ADMIN");
        jPanellogin.add(jRadioButton_admin_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));
        jPanellogin.add(txt_userName_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelanhlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanellogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanellogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelanhlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String getSDT(){
        return sdt;
    }
    public String getPass(){
        return password;
    }
    public String getUserName(){
        return userName;
                
    }
    private void btn_dangnhap_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhap_loginActionPerformed
        LoginController loginController = new LoginController();
        userName = txt_userName_login.getText();
        password = new String(txt_password_login.getPassword());
        if (userName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nhập Username !", "Thong bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nhập Password !", "Thong bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jRadioButton_student_login.isSelected()) {
            sdt = userName;
            if (loginController.dangNhapSinhVien(sdt, password)) {
                
                this.dispose();
                new jFSinhVien().setVisible(true);
                
                return;
            } else {
                JOptionPane.showMessageDialog(null, "UserName hoặc mật khẩu không chính xác !", "Thong bao", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else {

            if (loginController.dangNhapAdmin(userName, password)) {
                this.dispose();
                new Admin_menu().setVisible(true);
                return;
            } else {
                JOptionPane.showMessageDialog(null, "UserName hoặc mật khẩu không chính xác !", "Thong bao", JOptionPane.ERROR_MESSAGE);
                return;
            }

        }

    }//GEN-LAST:event_btn_dangnhap_loginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jRadioButton_admin_login.setSelected(true);
    }//GEN-LAST:event_formWindowOpened

    private void btn_thoat_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoat_loginActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_thoat_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login lg = new Login();
                lg.setLocationRelativeTo(null);
                lg.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangnhap_login;
    private javax.swing.JButton btn_thoat_login;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelanhlogin;
    private javax.swing.JPanel jPanellogin;
    private javax.swing.JRadioButton jRadioButton_admin_login;
    private javax.swing.JRadioButton jRadioButton_student_login;
    private javax.swing.JPasswordField txt_password_login;
    private javax.swing.JTextField txt_userName_login;
    // End of variables declaration//GEN-END:variables
}
